# CONFIG - Aplicação
app:
  search.pagination.default:
    page: 0
    numberRecords: 10

# CONFIG - Spring
spring:
  application.name: catalogo-api
  h2.console:
    enabled: true
    path: /h2-console
  jpa.hibernate.ddl-auto: validate
  datasource:
    url: jdbc:h2:file:/home/lucas/dev/java-springboot-project/catalogo/db
    username: sa
    password:


